# Generated by Django 6.0.4 on 2026-04-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact_wapda_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='bill_amount_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='bill_amount_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='bill_amount_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='bill_month_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='bill_month_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='bill_month_3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='wapda_bill_2',
            field=models.FileField(blank=True, null=True, upload_to='bills/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='wapda_bill_3',
            field=models.FileField(blank=True, null=True, upload_to='bills/'),
        ),
    ]
