# Generated by Django 6.0.4 on 2026-04-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_contact_lead_status_project_staffprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='bill_amount_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='bill_amount_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='bill_amount_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='monthly_bill',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
