# Generated by Django 6.0.4 on 2026-04-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_contact_bill_amount_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='total_load_watts',
            field=models.PositiveIntegerField(default=0, help_text='Calculated total peak load in Watts'),
        ),
    ]
