# Generated by Django 6.0.4 on 2026-04-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contact_total_load_watts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='appliance_data',
            field=models.JSONField(blank=True, default=dict, help_text='Structured appliance load JSON'),
        ),
    ]
