# Generated by Django 6.0.4 on 2026-05-01 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contact_appliance_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='account_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('hbl', 'Habib Bank Limited (HBL)'), ('ubl', 'United Bank Limited (UBL)'), ('mcb', 'MCB Bank Limited'), ('allied', 'Allied Bank Limited (ABL)'), ('meezan', 'Meezan Bank'), ('alfalah', 'Bank Alfalah'), ('standard_chartered', 'Standard Chartered'), ('askari', 'Askari Bank'), ('faysal', 'Faysal Bank'), ('bank_punjab', 'The Bank of Punjab (BOP)'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='cnic',
            field=models.CharField(blank=True, max_length=20, verbose_name='CNIC / ID Number'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated'), ('on_leave', 'On Leave'), ('resigned', 'Resigned')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField(help_text='Month and Year of the payroll (usually set to 1st of the month)')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commissions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='core.staffprofile')),
            ],
            options={
                'ordering': ['-month_year'],
                'unique_together': {('staff', 'month_year')},
            },
        ),
    ]
