# Generated by Django 6.0.2 on 2026-05-03 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_installationproject_sitereview_installationphoto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFinancials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
                ('items', models.JSONField(default=list)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='core.project')),
            ],
            options={
                'verbose_name': 'Project Financial',
                'verbose_name_plural': 'Project Financials',
                'ordering': ['-created_at'],
            },
        ),
    ]
