# Generated by Django 6.0.2 on 2026-05-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_projectfinancials'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='owner_name',
            field=models.CharField(blank=True, default='Engr M Hassan', max_length=100),
        ),
    ]
