# Generated by Django 6.0.2 on 2026-05-06 09:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_jobapplication_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending / Survey'), ('civil_works', 'Civil Works'), ('electrical_works', 'Electrical Works'), ('panel_installation', 'Panel Installation'), ('net_metering', 'Net Metering'), ('commissioning', 'Commissioning'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='ProjectPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Payment proof or details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.project')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
