# Generated by Django 6.0.2 on 2026-05-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_project_contract_value_alter_project_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
