# Generated by Django 6.0.4 on 2026-05-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_author_name_post_category_post_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (e.g. Unsplash)', null=True),
        ),
    ]
