# Generated by Django 6.0.4 on 2026-05-01 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('monthly_bill', models.DecimalField(decimal_places=2, max_digits=15)),
                ('lead_type', models.CharField(choices=[('quick', 'Quick Inquiry'), ('detailed', 'Detailed Engineering')], default='quick', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='proposals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='automation.lead')),
            ],
        ),
        migrations.CreateModel(
            name='SolarCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_size_kw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_units', models.PositiveIntegerField()),
                ('monthly_savings', models.DecimalField(decimal_places=2, max_digits=15)),
                ('annual_savings', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payback_years', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('panel_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculation', to='automation.lead')),
            ],
        ),
    ]
