# Generated by Django 6.0.4 on 2026-05-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='battery_option',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='total_load_watts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
