# Generated by Django 6.0.4 on 2026-05-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_lead_battery_option_lead_total_load_watts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='battery_option',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lead_type',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='monthly_bill',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='total_load_watts',
        ),
        migrations.AddField(
            model_name='lead',
            name='estimated_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='monthly_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='system_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
