# Generated by Django 6.0.4 on 2026-05-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_remove_lead_battery_option_remove_lead_lead_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='appliance_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
