# Generated by Django 6.0.2 on 2026-05-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_lead_appliance_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('survey_scheduled', 'Survey Scheduled'), ('closed', 'Closed (Won)'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
