# Generated by Django 6.0.4 on 2026-04-24 19:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_quotation_customer_user_quotation_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='monthly_savings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='roi_years',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
