# Generated by Django 6.0.4 on 2026-04-27 09:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_quotation_monthly_savings_quotation_roi_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='breaker_rating',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='breaker_type',
            field=models.CharField(blank=True, help_text='e.g., MCB, MCCB', max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='earth_bore_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='inverter_type',
            field=models.CharField(blank=True, help_text='e.g., Hybrid, On-Grid', max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='monthly_units',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='peak_load_kw',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='quotation',
            name='spd_type',
            field=models.CharField(blank=True, help_text='e.g., Type 1, Type 2', max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='structure_material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='structure_type',
            field=models.CharField(blank=True, help_text='e.g., L1, L2, L3, Custom', max_length=50),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='battery',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
