# Generated by Django 6.0.4 on 2026-04-28 17:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_quotation_breaker_rating_quotation_breaker_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax percentage to apply to subtotal', max_digits=5),
        ),
    ]
