# Generated by Django 6.0.4 on 2026-04-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0009_alter_quotation_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='load_details',
            field=models.JSONField(blank=True, default=dict, help_text='Appliance load details JSON'),
        ),
    ]
