# Generated by Django 6.0.4 on 2026-04-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0010_quotation_load_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='total_load_watts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
