# Generated by Django 6.0.4 on 2026-04-29 10:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0011_quotation_total_load_watts'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='db_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='db_size',
            field=models.CharField(blank=True, help_text='e.g., 6 Way, 12 Way', max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='earthing_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='include_pages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quotation',
            name='isolator_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='isolator_unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='mcb_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='mcb_unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='mccb_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='mccb_unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='miscellaneous_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tax_type',
            field=models.CharField(choices=[('percentage', 'Percentage (%)'), ('fixed', 'Fixed (PKR)')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='wiring_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
