# Generated by Django 6.0.4 on 2026-04-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0012_quotation_db_rate_quotation_db_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='breaker_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
