# Generated by Django 6.0.4 on 2026-04-30 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0013_quotation_breaker_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='change_notes',
            field=models.TextField(blank=True, help_text='Internal notes about what changed in this version.'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_final',
            field=models.BooleanField(default=False, help_text='Locks the quotation from further edits.'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_negotiation_mode',
            field=models.BooleanField(default=False, help_text='If true, allows manual rate and discount overrides.'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='negotiation_notes',
            field=models.TextField(blank=True, help_text='Notes specifically related to client negotiations.'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='parent_quotation',
            field=models.ForeignKey(blank=True, help_text='The original quotation this version was revised from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='quotations.quotation'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
