# Generated by Django 6.0.2 on 2026-05-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0014_quotation_change_notes_quotation_is_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='db_qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
